import streamlit as st
import pandas as pd
import pickle
import numpy as np
import os
from datetime import datetime

# PDF Libraries
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer, Image
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

# ================== CONFIG ==================
st.set_page_config(page_title="MEDIFLO - Maternal Health", layout="centered", page_icon="🤰")

# ================== LOAD MODEL ==================
model_path = os.path.join(os.path.dirname(__file__), "maternal_model.pkl")

@st.cache_resource
def load_model():
    try:
        with open(model_path, "rb") as f:
            return pickle.load(f)
    except FileNotFoundError:
        return None

model = load_model()

# ================== PDF FUNCTION ==================
def generate_maternal_pdf(df, prediction_text, name, age):
    filename = f"{name}_Maternal_Report.pdf"
    pdf = SimpleDocTemplate(filename, pagesize=A4, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30)
    styles = getSampleStyleSheet()
    elements = []

    # --- Styles ---
    title_style = ParagraphStyle("TitleStyle", fontSize=18, textColor=colors.darkred, alignment=1, spaceAfter=20)
    section_style = ParagraphStyle("SectionStyle", fontSize=12, fontName="Helvetica-Bold", spaceAfter=10, textColor=colors.black)
    label_style = styles["Normal"]

    # --- Header ---
    elements.append(Paragraph("MEDIFLO – Maternal Health Risk Report", title_style))
    
    # Patient Info Header
    info_data = [
        [f"Patient Name: {name}", f"Date: {datetime.now().strftime('%d-%m-%Y %H:%M')}"],
        [f"Age: {age}", "Gender: Female"]
    ]
    info_table = Table(info_data, colWidths=[250, 250])
    info_table.setStyle(TableStyle([('TEXTCOLOR', (0,0), (-1,-1), colors.grey), ('FONTSIZE', (0,0), (-1,-1), 10)]))
    elements.append(info_table)
    elements.append(Spacer(1, 20))

    # --- Clinical Parameters ---
    elements.append(Paragraph("Clinical Parameter Details", section_style))
    
    display_df = df.iloc[0].to_frame().reset_index()
    display_df.columns = ["Parameter", "Value"]
    
    table_data = [["Clinical Parameter", "Result"]] + display_df.values.tolist()
    table = Table(table_data, colWidths=[200, 150]) 

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
    ]))
    
    elements.append(table)
    elements.append(Spacer(1, 20))

    # --- Result Section ---
    elements.append(Paragraph("Risk Assessment Analysis", section_style))
    
    # Set color based on risk
    if "High" in prediction_text: result_color = colors.red
    elif "Mid" in prediction_text: result_color = colors.orange
    else: result_color = colors.green

    summary_data = [
        [Paragraph(f"<b>Final Assessment:</b>", label_style), Paragraph(f"<font color={result_color}><b>{prediction_text}</b></font>", label_style)],
    ]
    
    summary_table = Table(summary_data, colWidths=[200, 150])
    summary_table.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,0), (0,-1), colors.whitesmoke),
    ]))
    
    elements.append(summary_table)
    elements.append(Spacer(1, 40))

    # --- Footer ---
    elements.append(Paragraph("<b>Note:</b> This report is generated by an AI model and should be verified by a medical professional.", styles["Italic"]))
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("__________________________", label_style))
    elements.append(Paragraph("Authorized Signatory / Digital System", label_style))

    pdf.build(elements)
    return filename

# ================== UI ==================
st.title("🤰 Maternal Health Detection System")

tab1, tab2, tab3 = st.tabs(['🩺 Predict', '📂 Bulk Predict', '📊 Model Info'])

# ================== TAB 1: PREDICT ==================
with tab1:
    st.subheader("🧑‍⚕️ Patient Details")
    col1, col2 = st.columns(2)
    with col1:
        name = st.text_input("Full Name", placeholder="e.g. Jane Doe")
        age = st.number_input("Age", 10, 60, 25)
    with col2:
        st.write("") # Spacer
        st.info("System specifically calibrated for prenatal health indicators.")

    st.divider()
    st.subheader("🧪 Clinical Parameters")
    c1, c2, c3 = st.columns(3)
    with c1:
        sys_bp = st.number_input("Systolic BP", 70, 200, 120)
        dia_bp = st.number_input("Diastolic BP", 40, 120, 80)
    with c2:
        bs = st.number_input("Blood Sugar (mmol/L)", 3.0, 30.0, 7.0)
        temp = st.number_input("Body Temp (°F)", 95.0, 106.0, 98.6)
    with c3:
        heart_rate = st.number_input("Heart Rate", 40, 160, 75)

    if st.button("🚀 Analyze Health Risk", use_container_width=True):
        if name == "" or not model:
            st.warning("⚠️ Please provide a name and ensure the model is loaded.")
            st.stop()

        # Input Data Formatting
        input_data = pd.DataFrame([{
            'Age': age,
            'SystolicBP': sys_bp,
            'DiastolicBP': dia_bp,
            'BS': bs,
            'BodyTemp': temp,
            'HeartRate': heart_rate
        }])

        # Prediction
        prediction = model.predict(input_data)[0]
        
        # Mapping (Ensure this matches your training encoding)
        risk_map = {0: "Low Risk", 1: "Mid Risk", 2: "High Risk"}
        result = risk_map.get(prediction, "Unknown")

        st.subheader("📊 Result")
        if "High" in result:
            st.error(f"🔴 Result: {result}")
        elif "Mid" in result:
            st.warning(f"🟡 Result: {result}")
        else:
            st.success(f"🟢 Result: {result}")

        # PDF & Download
        try:
            pdf_path = generate_maternal_pdf(input_data, result, name, age)
            with open(pdf_path, "rb") as f:
                st.download_button(
                    "📄 Download PDF Report",
                    f,
                    file_name=f"{name}_MaternalReport.pdf",
                    mime="application/pdf"
                )
        except Exception as e:
            st.error(f"PDF Generation Error: {e}")

# ================== TAB 2: BULK ==================
with tab2:
    st.subheader("📂 Batch Prediction")
    st.file_uploader("Upload CSV file", type=["csv"])
    st.write("Upload a file with columns: Age, SystolicBP, DiastolicBP, BS, BodyTemp, HeartRate")

# ================== TAB 3: INFO ==================
with tab3:
    st.subheader("📊 Model Information")
    st.write("This model uses **Logistic Regression** trained on the UCI Maternal Health Risk dataset.")
    st.metric("Model Precision", "83%")